on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'
      - uses: actions/checkout@v3
      - name: Test
        run: go test -race -count 100 ./... -coverprofile .testCoverage.txt
